### ISSUE TITLE
Error while trying to upload and update egg

### ISSUE THREAD

**Issue by LeonKarabchevsky** [ShopRunner/apparate#16]
pparate.update_databricks_library.APIError: http 400: <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 400 </title>
</head>
<body>
<h2>HTTP ERROR: 400</h2>
<p>Problem accessing /api/1.2/libraries/upload. Reason:
<pre>    The V1 APIs for clusters and libraries are disabled. Please use the V2 APIs.</pre></p>
<hr />
</body>
</html>

**Comment by htorrence** [comment]
Hmm, the command still works on my machine, so I suspect Databricks is slowly rolling a change out on accounts. We're reaching out to Databricks to try and resolve it. Thanks for raising this!

**Comment by htorrence** [comment]
Update @LeonKarabchevsky - after talking with Databricks, they said that there are no plans to deprecate the V1 apis, but that they are only available on AWS (not Azure). Are you running on Azure? 

If that's the case I'll add a note to the readme + docs that unfortunately at this time the tool will only work for AWS.

**Comment by LeonKarabchevsky** [comment]
Yes I'm running on Azure.
Thank you for the quick reply !

**Comment by htorrence** [comment]
Note in docs + readme added in PR#20
