### ISSUE TITLE
pip install apparate error

### ISSUE THREAD

**Issue by LeonKarabchevsky** [ShopRunner/apparate#17]
Collecting apparate
  Downloading https://files.pythonhosted.org/packages/0e/ac/33ba73da58039a5d0fdc2a247ed1da589e791540c40fbb9a5a622d6fb699/apparate-2.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-cSEU2b/apparate/setup.py", line 9, in <module>
        with open('LICENSE.txt') as l:
    IOError: [Errno 2] No such file or directory: 'LICENSE.txt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-cSEU2b/apparate/

**Comment by htorrence** [comment]
Ah yep, looks like we're missing a manifest file - I'll get that fixed. In the mean time installing the wheel should work. Thanks!

**Comment by htorrence** [comment]
fixed in PR#20
